services:
  - type: web
    name: curelink-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_TOOL_MODEL
        value: llama-3.3-70b-versatile
      - key: HF_TOKEN
        sync: false
      - key: HUGGINGFACE_MODEL
        value: HuggingFaceH4/zephyr-7b-beta
      - key: STRIPE_SECRET_KEY
        sync: false

  - type: static
    name: curelink-frontend
    staticPublishPath: ./dist
    buildCommand: cd frontend && npm install && npm run build
    envVars:
      - key: VITE_API_URL
        value: https://curelink-backend-v2.onrender.com
